export const SITE = {
  website: "https://harrysui.me/",
  author: "Harry",
  email: "muggle6594@gmail.com",
  profile: "https://github.com/mxggle",
  desc: "A blog about language learning, AI, and thoughts.",
  title: "Harry's Blog",
  ogImage: "devharry-og.webp",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000, // 15 minutes
  showArchives: true,
  showGalleries: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit post",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Tokyo",
  introAudio: {
    enabled: false,
    src: "/audio/intro-web.mp3",
    label: "INTRO.MP3",
    duration: 30,
  },
} as const;
